### ISSUE TITLE
include examples do not decode in jwt.io

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-jws-voucher#1]
Removing the \\\n manually in jwt.io from voucher_request.b01 does not result in a decode voucher request. 
Instead we see:

````
"{\"iey�]��X�\u0019\\�\\�\\]Y\\�\u000e���X�\u0019\\���\u001eȘܙX]\u0019Y\u000b[ۈ��\b�\u0003#\u0002�\u0013\u0002�#%C\u0003#�3s�3��\u0003\u0003\u0005�\"�\u0002&���6R#�\u0002&TG2���gT!\u001dU�I�8�\u0014��\rD�􈰀�͕ɥ����յ��Ȉ耈���������\"}}"
```

**Comment by siethower** [comment]
Fixed or workaround by "fixing example A1, A2, A3 by direct insert into mkd": 
https://github.com/anima-wg/anima-jws-voucher/commit/b324bf1acc205ef8bd505d3896888b5605b5b01d

**Comment by siethower** [comment]
Examples are manually included, I think this can be closed.
